"""
Remove assignments until we are ready

Revision ID: 8ce3d848d256
Revises: 2c3ae239a698
Create Date: 2020-03-10 16:03:37.493012
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce3d848d256'
down_revision = '2c3ae239a698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('desc', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('studentClasses', sa.VARCHAR(length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
